# Generated by Django 4.0.4 on 2024-02-03 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libeiki', '0002_alter_commentaire_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='date_com',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
